### ISSUE TITLE
Lazily initialize TextKit classes upon link tap

### ISSUE THREAD

**Issue by lbrndnr** [indragiek/INDLinkLabel#3]
Hi Indragie,

I was getting curious when I saw your tweets yesterday and tried to solve the issue another way. I wrote a little [class](https://www.dropbox.com/s/ytpa589zmexht4f/INDLinkLabel.playground.zip?dl=0) as a proof of concept. Because it creates the essential TextKit classes when it is tapped, it can easily be transformed into an extension instead of a subclass of UILabel. 

Let me know what you think

**Comment by indragiek** [comment]
Hey, sorry for the late response. I considered something like this but didn't go with this approach for a few reasons:
1. Making the assumption that the text container size is the same as the frame size of the label could be fragile. It works at the moment, but if they decided to add something like a `textContainerInset` property to `UILabel` at some point, this would break.
2. `-drawRect:` override is still required to draw the highlight over the link that is tapped, so this couldn't easily become an extension.

**Comment by indragiek** [comment]
@larcus94 I've thought about this some more, especially considering some bugs that are not in `UILabel` that `INDLinkLabel` currently has (like #1 and #2) and I think I may just make this a `UILabel` subclass as requested. As mentioned above, it can't be an extension because of the `-drawRect:` override. I'm working on it right now and will let you know when I've made progress.

Thanks for bringing this up!

**Comment by lbrndnr** [comment]
No worries at all!

Oh yeah, forgot about `-drawRect:` but I think the advantages are obvious nevertheless. Glad you chose to implement it this way :)
